version: '3.8'

services:
  server-bot:
    build: ./
    command: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - PASS=necompanydevteampassword
    ports:
      - "5437:5432"  # Changed from 5436 to 5437
